### ISSUE TITLE
Are there any tools in which this experimentation results are used? What were your inferences from these experiments?

### ISSUE THREAD

**Issue by nodeCodeNinja** [Kitware/spark-mpi-experimentation#3]
As always you are going great work!

I think it would be interesting to the community to know, 
Are there any tools in which this experimentation results are used? 
What were your inferences from these experiments?

**Comment by jourdain** [comment]
Spark tends to have so much overhead and does not play nice with MPI expectation. We managed to build a proof of concept that was relying on Spark to manage the deployment of various processes while interconnecting those process with MPI, but due to the resilient nature of Spark, it could happen that Spark will kill a MPI process because it thought it was dead while it was just busy. Therefore running such setup was fairly flicky.
